#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 24 14:50:03 2019

@author: janne
"""
import numpy as np
import mesa_reader as mr

# load the profile file into a MesaData instance
p = mr.MesaData('/home/janne/Gunter_project/gunther_project/LOGS/profile1.data')

# access the temperature column of data
temperatures = 10 ** p.logT